"audio or video avoids automatically playing audio" (80f0bf / aaa1bf / 4c31df): Feedback from TF.
act-rules/act-rules.github.io pull request #1447
Opened 2020-09-14 14:20 UTC by Jym77

* Add definition of "attribute value" for IDL attributes, and use it in the rules.
* Replace formulation of  source using "media resource".
* Replace "mechanism" by "instrument".
* Add an assumption that alternance of short sounds and pauses is not good.
* Add assumption that the mechanism must be located in the same page, and exposed to users.

Closes issue(s):

- closes #https://github.com/w3c/wcag-act/issues/456
- closes #1016 

Need for Final Call:
This will require a 1 week Final Call (large editorial changes and clarifications).

---

## Pull Request Etiquette

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [X] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2020-09-16 07:59 UTC, kasperisager approved these changes

2020-09-16 19:48 UTC, WilcoFiers submitted a review, later dismissed
Editorial stuff

2020-09-16 19:48 UTC, WilcoFiers commented on _rules/auto-play-audio-has-control-mechanism-4c31df.md
> +This `video` element has a [instrument][] to pause, stop, or turn the audio volume off but the mechanism is not visible.
```suggestion
This `video` element has an [instrument][] to pause, stop, or turn the audio volume off but the mechanism is not visible.
```

2020-09-16 19:48 UTC, WilcoFiers commented on _rules/auto-play-audio-has-control-mechanism-4c31df.md
> +This `video` element has a [instrument][] to pause, stop, or turn the audio volume off but its `button` elements do not have accessible names.
```suggestion
This `video` element has an [instrument][] to pause, stop, or turn the audio volume off but its `button` elements do not have accessible names.
```

2020-09-16 19:48 UTC, WilcoFiers commented on _rules/auto-play-audio-has-control-mechanism-4c31df.md
> +This `video` element has a [instrument][] to pause, stop, or turn the audio volume off but the mechanism is not included in the accessibility tree.
```suggestion
This `video` element has an [instrument][] to pause, stop, or turn the audio volume off but the mechanism is not included in the accessibility tree.
```

2020-09-16 19:53 UTC, kasperisager commented on _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
> +- a `paused` [attribute value][] of `false`; and
It refers to an IDL attribute, not a content attribute, as covered in the definition of "attribute value":

> The attribute value of an IDL attribute is the value returned on getting it. Note that when an IDL attribute reflects a content attribute, they have the same attribute value.

2020-09-21 13:41 UTC, Jym77 commented on _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
> +- a `paused` [attribute value][] of `false`; and
Which is why the definition of "attribute value" has been updated in that very PR in order to handle IDL attributes…

2020-09-23 08:56 UTC, daniel-montalvo requested changes
Minor editorial suggestions

2020-09-23 08:56 UTC, daniel-montalvo commented on _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
> +- This rule assumes that the [mechanism](https://www.w3.org/TR/WCAG21/#dfn-mechanism) to control the sound must be visible and accessible in order to be effective and usable by all kind of users. If
```suggestion
- This rule assumes that the [mechanism](https://www.w3.org/TR/WCAG21/#dfn-mechanism) to control the sound must be visible and accessible in order to be effective and usable by all kinds of users. If the mechanism is hidden to some users, it is possible to fail this rule but still satisfy [Success Criterion 1.4.2 Audio Control][sc142].
```

2020-09-23 08:56 UTC, daniel-montalvo commented on _rules/auto-play-audio-has-control-mechanism-4c31df.md
> +This `video` element has an [instrument][] to pause, stop, or turn the audio volume off but the mechanism is not visible.
```suggestion
This `video` element has an [instrument][] to pause, stop, or turn the audio volume off but the [instrument][] is not visible.
```

2020-09-23 08:56 UTC, daniel-montalvo commented on _rules/auto-play-audio-has-control-mechanism-4c31df.md
> +This `video` element has an [instrument][] to pause, stop, or turn the audio volume off but the mechanism is not included in the accessibility tree.
```suggestion
This `video` element has an [instrument][] to pause, stop, or turn the audio volume off but the [instrument][] is not included in the accessibility tree.
```

2020-09-23 09:20 UTC, daniel-montalvo approved these changes

2020-09-24 09:35 UTC, WilcoFiers commented on _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
> +- a `paused` [attribute value][] of `false`; and
Fair enough! My mistake.

2020-09-24 09:37 UTC, WilcoFiers approved these changes

2020-09-24 12:05 UTC, Jym77 commented
Final Call ends on October 1st.

2020-10-01 08:53 UTC, Jym77 commented
Final Call has ended. Merging.

2020-10-01 08:54 UTC, merged