visible-label: fix minor whitespace
act-rules/act-rules.github.io pull request #1452
Opened 2020-09-17 13:16 UTC by WilcoFiers

Passed example 2 doesn't seem like it needs that whitespace character. Example 1 has it covered.

Need for Final Call: 1 week

2020-09-20 15:20 UTC, jeeyyy submitted a review, later dismissed

2020-09-21 13:46 UTC, Jym77 requested changes

2020-09-21 13:46 UTC, Jym77 commented on _rules/visible-label-in-accessible-name-2ee8b8.md
> +<a href="https://act-rules.github.io/" aria-label="act rules">ACT rules</a>
I think I'd prefer to remove the extra space in Passed example 1 and keep it here, updating the description to "ignoring case and trailing spaces".

Reason: keep the first Passed Example as "the simplest way" to pass the rule helps humans reading it. First show the most basic case, then the weird stuff.

2020-09-23 10:49 UTC, Jym77 approved these changes

2020-09-23 11:23 UTC, carlosapaduarte approved these changes

2020-09-23 15:37 UTC, maryjom approved these changes

2020-10-04 14:32 UTC, jeeyyy approved these changes

2020-10-05 08:55 UTC, merged