Add Accessibility support note on valid but empty aria-labelledby
act-rules/act-rules.github.io pull request #1462
Opened 2020-09-24 12:40 UTC by Jym77

An an accessibility support note on discrepancies when `aria-labelledby` refers to an existing element with empty content.

Closes issue(s):

- closes #1203

Need for Final Call:
This will not require a Final Call (change to accessibility support only).

---

## Pull Request Etiquette

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [X] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2020-09-24 12:43 UTC, WilcoFiers requested changes
Minor suggestion.

2020-09-24 12:43 UTC, WilcoFiers commented on _rules/heading-non-empty-accessible-name-ffd0e9.md
> +- The [accessible name and description computation][] suggest that if an `aria-labelledby` attribute refers to an existing but empty element, the computation should stop and return and empty name wit
```suggestion
- The [accessible name and description computation][] suggest that if an `aria-labelledby` attribute refers to an existing but empty element, the computation should stop and return and empty name without defaulting to the next steps. Several user agents and assistive technologies chose to use the next step in the computation in this case.
```

2020-09-24 12:47 UTC, carlosapaduarte requested changes
typo

2020-09-24 12:47 UTC, carlosapaduarte commented on _rules/heading-non-empty-accessible-name-ffd0e9.md
> +- The [accessible name and description computation][] suggest that if an `aria-labelledby` attribute refers to an existing but empty element, the computation should stop and return and empty name wit
```suggestion
- The [accessible name and description computation][] suggest that if an `aria-labelledby` attribute refers to an existing but empty element, the computation should stop and return an empty name without defaulting to the next steps. Several user agents and assistive technologies chose to use the next step in the computation in this case.
```

2020-09-24 12:54 UTC, WilcoFiers approved these changes

2020-09-24 12:55 UTC, carlosapaduarte approved these changes

2020-09-25 13:21 UTC, ajanec01 approved these changes

2020-09-29 06:09 UTC, kasperisager approved these changes

2020-09-29 06:47 UTC, merged