explicit-svg-img, add <text> example
act-rules/act-rules.github.io pull request #1467
Opened 2020-09-30 09:54 UTC by WilcoFiers

This example addresses a question that came up during yesterday's AGWG call. 

Need for Final Call: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2020-09-30 09:56 UTC, kasperisager approved these changes

2020-09-30 10:33 UTC, Jym77 requested changes

2020-09-30 10:33 UTC, Jym77 commented on _rules/explicit-SVG-image-non-empty-accessible-name-7d6734.md
> +This `svg` element has an [explicit role][] of `img` has an empty (`""`) [accessible name][]. The SVG `text` element is not used in computing the accessible name.
```suggestion
This `svg` element with an [explicit role][] of `img` has an empty (`""`) [accessible name][]. The SVG `text` element is not used in computing the accessible name.
```
(avoid double verb)

2020-10-01 06:50 UTC, Jym77 approved these changes

2020-10-04 14:22 UTC, jeeyyy approved these changes

2020-10-12 08:27 UTC, merged