scrollable-keyboard-acc: add accessibility support note
act-rules/act-rules.github.io pull request #1478
Opened 2020-10-09 12:30 UTC by WilcoFiers

This feedback was provided by the ACT Task Force. Firefox it turns out, will add elements with a scrollbar to the sequential focus navigation.

Need for Final Call: none

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2020-10-09 18:37 UTC, maryjom commented on _rules/scrollable-element-keyboard-accessible-0ssw9k.md
> +Some browsers will automatically make any scrollable element focusable to ensure keyboard accessibility. Those elements become inaccessible only if they have negative number as a tabindex [attribute
Suggest editing this to read: 

However, the browser does not automatically make the scrollable element focusable when it has a negative number as a tabindex [attribute value][].

2020-10-09 18:38 UTC, maryjom requested changes
See my comment for suggested changes.

2020-10-11 10:23 UTC, carlosapaduarte requested changes
Agree with @maryjom suggestion. Will approve after the change.

2020-10-12 08:39 UTC, carlosapaduarte approved these changes

2020-10-13 14:40 UTC, jeeyyy submitted a review, later dismissed

2020-10-13 14:40 UTC, jeeyyy commented on _rules/scrollable-element-keyboard-accessible-0ssw9k.md
> +Some browsers will automatically make any scrollable element focusable to ensure keyboard accessibility. However, the browser does not included these elements in [sequential focus navigation][] when
worth linking scrollable element to the glossary item

2020-10-13 14:40 UTC, jeeyyy commented on _rules/scrollable-element-keyboard-accessible-0ssw9k.md
> +Some browsers will automatically make any scrollable element focusable to ensure keyboard accessibility. However, the browser does not included these elements in [sequential focus navigation][] when
```suggestion
Some browsers will automatically make any scrollable element focusable to ensure keyboard accessibility. However, the browser does not include these elements in [sequential focus navigation][] when it has a negative number as a tabindex [attribute value][].
```

2020-10-15 09:14 UTC, Jym77 approved these changes

2020-10-15 11:30 UTC, merged