aria-required-owned: remove implicit exception
act-rules/act-rules.github.io pull request #1479
Opened 2020-10-13 09:46 UTC by WilcoFiers

Closes #1413

Need for Final Call: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2020-10-13 12:04 UTC, Jym77 approved these changes

2020-10-13 14:41 UTC, jeeyyy submitted a review, later dismissed

2020-10-14 19:43 UTC, carlosapaduarte submitted a review, later dismissed

2020-10-15 11:27 UTC, Jym77 requested changes
The Background note at https://github.com/act-rules/act-rules.github.io/pull/1479/files#diff-b67a2f24a6ac7b3ff85d5593f4f29edc3007d36f94ff5200ae39fd8ae2f0048eL52 must be removed or somehow adapted since it is now incorrect.

2020-10-15 12:39 UTC, Jym77 approved these changes

2020-10-19 12:31 UTC, carlosapaduarte approved these changes

2020-10-19 12:44 UTC, jeeyyy approved these changes

2020-10-23 09:27 UTC, merged