Unifying listed conditions
act-rules/act-rules.github.io pull request #1510
Opened 2020-11-30 16:41 UTC by daniel-montalvo

Following up on work from #1506 , these are updates to some rules that are not currently following listing conditions that we agreed on #1275 

---

Closes issue(s):

N/A

Need for Final Call:
This will require a 1 week Final Call << small changes affecting a small number of test cases, if in doubt do not use this. >>

---

## Pull Request Etiquette

### **When creating PR:**

- [x] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [x] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [x] Add yourself (and co-authors) as "Assignees" for PR.
- [x] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [x] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [x] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2020-12-01 11:50 UTC, WilcoFiers requested changes
You got a couple of 'm mixed up. Also, can't approve this until the applicability phrasing changes are no longer part of this PR. You can wait for #1506 to get merged, but you might have a heck of a lot of merge conflicts on your hands after that PR merges.

2020-12-01 11:50 UTC, WilcoFiers commented on _rules/audio-as-media-alternative-afb423.md
> +This rule applies to every [non-streaming](#non-streaming-media-element) `audio` element for which all of the following are true:
```suggestion
This rule applies to every [non-streaming](#non-streaming-media-element) `audio` element for which one of the following are true:
```

2020-12-01 11:50 UTC, WilcoFiers commented on _rules/audio-text-alternative-e7aa44.md
> +This rule applies to any [non-streaming](#non-streaming-media-element) `audio` element for which all of the following are true:
```suggestion
This rule applies to any [non-streaming](#non-streaming-media-element) `audio` element for which one of the following are true:
```

2020-12-01 11:50 UTC, WilcoFiers commented on _rules/audio-transcript-2eb176.md
> +This rule applies to every [non-streaming](#non-streaming-media-element) `audio` element for which all of the following are true:
```suggestion
This rule applies to every [non-streaming](#non-streaming-media-element) `audio` element for which one of the following are true:
```

2020-12-01 11:50 UTC, WilcoFiers commented on _rules/form-field-non-empty-accessible-name-e086e5.md
> +This rule applies to any element that is [included in the accessibility tree](#included-in-the-accessibility-tree), and that has one of the following [semantic roles][]:
I don't think this should be written out in a list like this. I think we've more recently set a president that in cases where we have a bunch of rules, we put the list in the background, and have the applicability say what the conditions are for the roles. This rule has it currently flipped the wrong way around.

2020-12-01 11:50 UTC, WilcoFiers commented on _rules/html-page-lang-valid-bf051a.md
> +This rule applies to any [document element](https://dom.spec.whatwg.org/#document-element) if it is an `html` element for which one of the following is true:
```suggestion
This rule applies to any [document element](https://dom.spec.whatwg.org/#document-element) if it is an `html` element for which all of the following is true:
```

2020-12-01 11:50 UTC, WilcoFiers commented on _rules/html-page-lang-xml-lang-match-5b7ae0.md
> +This rule applies to any [document element](https://dom.spec.whatwg.org/#document-element) if it is an `html` element for which one of the following is true:
```suggestion
This rule applies to any [document element](https://dom.spec.whatwg.org/#document-element) if it is an `html` element for which all of the following is true:
```

2021-09-16 13:29 UTC, daniel-montalvo commented
Closing as it will create a lot of conflicts. Will open a separate one for the remaining rules.

2021-09-16 13:29 UTC, closed without merging