"Element with `lang` attribute has valid language tag" (de46e4): Apply to body and ignore attributes with no effect
act-rules/act-rules.github.io pull request #1547
Opened 2021-02-11 10:16 UTC by Jym77

Align the "lang valid" rule with the newer "lang matches default" one by
- also applying on `body` itself;
- only checking `lang` attributes who affect some text.

Closes issue(s):

- closes #1520 
- closes #1525 

Need for Final Call:
This will require a 1 week Final Call (small fixes to Applicability)

---

## Pull Request Etiquette

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [X] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [X] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-02-21 21:10 UTC, ajanec01 approved these changes

2021-04-12 09:23 UTC, WilcoFiers approved these changes

2021-05-07 19:58 UTC, carlosapaduarte requested changes
Some colons missing

2021-05-07 19:58 UTC, carlosapaduarte commented on _rules/element-lang-valid-de46e4.md
> +- **descendant** the element is an [inclusive descendant][] in the [flat tree][] of a `body` element; and
```suggestion
- **descendant**: the element is an [inclusive descendant][] in the [flat tree][] of a `body` element; and
```

2021-05-07 19:58 UTC, carlosapaduarte commented on _rules/element-lang-valid-de46e4.md
> +- **content type** the element has an associated [node document][] with a [content type][] of `text/html`; and
```suggestion
- **content type**: the element has an associated [node document][] with a [content type][] of `text/html`; and
```

2021-05-07 19:58 UTC, carlosapaduarte commented on _rules/element-lang-valid-de46e4.md
> +- **text** there is some non-empty [text inheriting its programmatic language][] from the element.
```suggestion
- **text**: there is some non-empty [text inheriting its programmatic language][] from the element.
```

2021-06-02 19:27 UTC, carlosapaduarte approved these changes

2021-06-10 12:00 UTC, Jym77 commented
Call for review ends on June 17th.

2021-06-17 10:13 UTC, Jym77 commented
Call for review ended. Merging.

2021-06-17 10:14 UTC, merged