updated video failed example 1
act-rules/act-rules.github.io pull request #1557
Opened 2021-03-19 16:25 UTC by zalmeraj

Need for Final Call: None

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-03-19 16:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1557) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1557) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/act-rules/act-rules.github.io?pullRequest=1557) it.</sub>

2021-04-01 09:53 UTC, ajanec01 approved these changes

2021-04-08 11:28 UTC, Jym77 requested changes
If you feel confident, feel free to update the other examples description in the same way 👍

2021-04-08 11:28 UTC, Jym77 commented on _rules/video-alternative-for-visual-c5a4ea.md
> +This 'video' element has an incorrect audio description.
```suggestion
This `video` element has an incorrect audio description.
```
Text enclosed in backticks is rendered as code, which is what we want here as we refer to the name of the HTML element.
('video' vs `video`)

2021-04-12 07:25 UTC, Jym77 approved these changes
Github "pro tip":
After making changes requested by a review, you can
1. "dismiss" that review. This happens near the bottom of the page in the drop-down with the "1 change requested" label. => This ensures that other potential reviewers see that these concerns have been addressed; some reviewers are reluctant to review a PR which already has changes requested since it can sometimes feel "double work".
2. "re-request" a review from the same reviewer. This happens near the top of the page, by using the "recycling" arrows next to that reviewer's name. => This ensures that this reviewer gets notified that their concern have been handle and they need to get another look at it.

(no worries if you forget to do it)

2021-04-12 09:15 UTC, WilcoFiers approved these changes

2021-04-12 09:16 UTC, WilcoFiers commented
Looks like this is good to go.

2021-04-12 09:16 UTC, merged