update video passed example 4
act-rules/act-rules.github.io pull request #1558
Opened 2021-03-19 16:26 UTC by susanatx

editorial change

Need for Final Call:

This will not require a Final Call re: editorial change

---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-03-19 16:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1558) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1558) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/act-rules/act-rules.github.io?pullRequest=1558) it.</sub>

2021-04-08 11:25 UTC, Jym77 requested changes

2021-04-08 11:25 UTC, Jym77 commented on _rules/video-alternative-for-visual-c5a4ea.md
> +The video element describes some of the text on the same page. The text identifies the video as an alternative.
```suggestion
This video element describes some of the text on the same page. The text identifies the video as an alternative.
```
We normally use demonstrative article in test cases description: https://act-rules.github.io/pages/design/rule-design/#test-cases

2022-03-01 11:23 UTC, daniel-montalvo approved these changes

2022-03-02 15:53 UTC, WilcoFiers commented on _rules/video-alternative-for-visual-c5a4ea.md
> +
```suggestion
```

2022-03-02 15:54 UTC, WilcoFiers commented on _rules/video-alternative-for-visual-c5a4ea.md
> +
```suggestion
```

2022-03-08 09:25 UTC, WilcoFiers approved these changes

2022-03-08 10:16 UTC, HelenBurge approved these changes

2022-03-31 10:54 UTC, Jym77 commented
Editorial changes to example description, no need for Call for Review. Merging.

2022-03-31 10:54 UTC, merged