Minor formatting changes to Expectations section
act-rules/act-rules.github.io pull request #1561
Opened 2021-03-19 16:44 UTC by SameeraKamra

Added ;(and | or) at the end of the list:
For each test target, the [outcome](#outcome) of at least one of the following rules is passed:

- [`Video` Element Visual Content Has Audio Description](https://act-rules.github.io/rules/1ea59c);(and | or)
- [`Video` Element Visual Content Has Transcript](https://act-rules.github.io/rules/1a02b0);(and | or)
- [`Video` Element Visual Content Has Description Track](https://act-rules.github.io/rules/f196ce);(and | or)
- [`Video` Element Content Is Media Alternative For Text](https://act-rules.github.io/rules/ab4d13)

Need for Final Call:
No need for Final Call
---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-03-19 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1561) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1561) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/act-rules/act-rules.github.io?pullRequest=1561) it.</sub>

2021-03-19 16:54 UTC, ajanec01 commented on _rules/video-alternative-for-visual-c5a4ea.md
> +- [`Video` Element Visual Content Has Audio Description](https://act-rules.github.io/rules/1ea59c);(and | or)
```suggestion
- [`Video` Element Visual Content Has Audio Description](https://act-rules.github.io/rules/1ea59c); or
```

2021-03-19 16:54 UTC, ajanec01 commented on _rules/video-alternative-for-visual-c5a4ea.md
> +- [`Video` Element Visual Content Has Transcript](https://act-rules.github.io/rules/1a02b0);(and | or)
```suggestion
- [`Video` Element Visual Content Has Transcript](https://act-rules.github.io/rules/1a02b0); or
```

2021-03-19 16:56 UTC, ajanec01 requested changes
Hey Sameera.
Something I didn't mention before, it's a good practice to refer to the rule you're editing in the pull requests title or the description.

2021-03-19 16:56 UTC, ajanec01 commented on _rules/video-alternative-for-visual-c5a4ea.md
> +- [`Video` Element Visual Content Has Description Track](https://act-rules.github.io/rules/f196ce);(and | or)
```suggestion
- [`Video` Element Visual Content Has Description Track](https://act-rules.github.io/rules/f196ce); or
```

2021-03-22 08:59 UTC, ajanec01 approved these changes

2021-03-22 16:33 UTC, SameeraKamra commented
Please suggest the next steps on this pull request. Thanks!

2021-04-08 11:13 UTC, Jym77 requested changes

2021-04-08 11:13 UTC, Jym77 commented on _rules/video-alternative-for-visual-c5a4ea.md
>  - [`Video` Element Content Is Media Alternative For Text](https://act-rules.github.io/rules/ab4d13)
```suggestion
- [`Video` Element Content Is Media Alternative For Text](https://act-rules.github.io/rules/ab4d13).
```
Last one should end up with full period.

2021-07-21 08:35 UTC, WilcoFiers approved these changes

2021-07-22 13:28 UTC, colabottles approved these changes

2021-07-22 13:49 UTC, merged

2021-07-26 21:44 UTC, kherr-a11y reviewed
Agreed