Editorial fixes that `lang` of elements- de46e4
act-rules/act-rules.github.io pull request #1584
Opened 2021-04-26 08:47 UTC by ajanec01

Minor editorial fixes to the applicability section of [Element with `lang` attribute has valid language tag](https://act-rules.github.io/rules/de46e4).

Updating listed conditions.

No need for the final call.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-04-27 11:50 UTC, WilcoFiers submitted a review, later dismissed

2021-04-27 11:50 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +- **visible or included in the accessibility tree**: the element has a [text node][] as a [descendant][] in the [flat tree][] that is [visible][] or [included in the accessibility tree][].
This one's a little wordy. Maybe this?

```suggestion
- **available**: the element has a [text node][] as a [descendant][] in the [flat tree][] that is [visible][] or [included in the accessibility tree][].
```

2021-05-05 10:26 UTC, WilcoFiers approved these changes

2021-05-06 08:14 UTC, Jym77 requested changes
I'll make these changes as part of #1547 instead to avoid merge conflicts.

2021-05-06 08:20 UTC, closed without merging