Editorial changes to Graphics with no text 0va7u6
act-rules/act-rules.github.io pull request #1592
Opened 2021-05-02 15:35 UTC by ajanec01

Editorial changes to [HTML graphics contain no text](https://act-rules.github.io/rules/0va7u6#rendered-image-resource) + fixing source location for a couple of examples.

No need for the final call.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-05-05 10:26 UTC, WilcoFiers approved these changes

2021-05-06 08:13 UTC, Jym77 approved these changes

2021-05-07 19:14 UTC, carlosapaduarte requested changes
Still a couple of typos

2021-05-07 19:14 UTC, carlosapaduarte commented on _rules/image-no-text-0va7u6.md
> +This rules applies to any [rendered image resources][] in a [web page][].
```suggestion
This rule applies to any [rendered image resources][] in a [web page][].
```

2021-05-10 11:41 UTC, carlosapaduarte approved these changes

2021-05-10 14:31 UTC, merged