Instrument accessibility note
act-rules/act-rules.github.io pull request #1632
Opened 2021-05-27 14:14 UTC by Jym77

Add a note in the definition of instrument, and the rules using it, to indicate that instruments should be accessible.

Closes issue(s):

- closes #1524 

Need for Final Call:
This will not require a Final Call (editorial changes)

---

## Pull Request Etiquette

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [X] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [X] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-05-31 11:22 UTC, WilcoFiers approved these changes

2021-05-31 11:22 UTC, WilcoFiers commented on pages/glossary/instrument.md
> +#### Background
This is going to result in a duplicate ID, unfortunately. We don't have a fix for this yet. Maybe change this to:

```suggestion
#### Background About Instrument
```

2021-05-31 11:23 UTC, WilcoFiers submitted a review, later dismissed
Wrong button.

2021-06-02 18:38 UTC, carlosapaduarte requested changes
Typo

2021-06-02 18:38 UTC, carlosapaduarte commented on pages/glossary/instrument.md
> +This definition is a more restrictive version of WCAG's definition of [mechanism][], notably restricting it to the current document. WCAG has a note that "The mechanism needs to meet all success crit
```suggestion
This definition is a more restrictive version of WCAG's definition of [mechanism][], notably restricting it to the current document. WCAG has a note that "The mechanism needs to meet all success criteria for the conformance level claimed." This includes all the level A criteria such as [Success Criterion 2.1.1 Keyboard][sc211] (the mechanism must be keyboard accessible) or [Success Criterion 4.1.2 Name, Role, Value][sc412] (the mechanism must be exposed to assistive technologies and have an accessible name). This definition, and the rules using it, leaves these extra requirements out. This avoids reporting the same component twice for the same reason (e.g., missing an accessible name) under two different rules and Success Criteria, and helps pinpoint the error related to each Success Criterion. Instruments should nonetheless be fully accessible at the correct conformance level (depending on the rule using them).
```

2021-06-15 10:15 UTC, WilcoFiers submitted a review, later dismissed

2021-06-15 10:15 UTC, WilcoFiers commented on _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
> +The [instruments][instrument] used to pass this rule (if any), must meet all level A Success Criteria in order to fully satisfy [Success Criterion 1.4.2 Audio Control][sc142]. These extra requirement
```suggestion
The [instruments][instrument] used to pass this rule (if any), must meet all level A Success Criteria in order to fully satisfy [Success Criterion 1.4.2 Audio Control][sc142]. These extra requirements are left out of this rule, and should be tested separately.
```

2021-06-18 17:04 UTC, carlosapaduarte approved these changes

2021-06-18 21:54 UTC, ajanec01 approved these changes

2021-06-22 09:52 UTC, WilcoFiers approved these changes

2021-06-25 11:06 UTC, merged