Correcting minor typos in [ee13b5]
act-rules/act-rules.github.io pull request #1635
Opened 2021-05-29 21:13 UTC by ajanec01

Minor editorial issues in [video element visual-only content has transcript](https://act-rules.github.io/rules/ee13b5).

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-05-31 11:09 UTC, WilcoFiers approved these changes

2021-06-02 18:31 UTC, carlosapaduarte approved these changes

2021-06-03 12:22 UTC, tbostic32 requested changes
Could you change `yaws` to `yawns` in the examples?

2021-06-03 14:03 UTC, Jym77 approved these changes

2021-06-03 14:52 UTC, merged