autocomplete: remove invalid example
act-rules/act-rules.github.io pull request #1653
Opened 2021-06-18 11:55 UTC by WilcoFiers

This example should have been removed when we changed the rule to no longer require the autocomplete be on an appropriate input type.

Need for Final Call: 1 week

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-06-18 15:57 UTC, carlosapaduarte approved these changes

2021-06-18 21:26 UTC, ajanec01 requested changes
I think the original idea was to catch an input with incorrect programmatic purpose. Yes, the example is wrong but  I feel that we should change it to:
```
<label>Email<input autocomplete="impp" /><label>
```

2021-06-22 21:32 UTC, ajanec01 approved these changes

2021-06-24 12:22 UTC, Jym77 approved these changes

2021-07-15 13:38 UTC, merged