Replace "Final Call" by "Call for Review" in PR template and Process document
act-rules/act-rules.github.io pull request #1692
Opened 2021-08-19 12:38 UTC by Jym77

Since we now call them "Call for Review" 😃 

Closes issue(s):

- N/A

Need for Final Call:
This will not require a Final Call (change to process documents)

---

## Pull Request Etiquette

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [X] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-08-19 12:39 UTC, Jym77 commented
@WilcoFiers #461 should probably be updated to replace "See all Pull Requests marked as Final Call here" by "See all Pull Requests marked as **Call for Review** here"

2021-08-19 14:02 UTC, WilcoFiers approved these changes

2021-08-24 08:07 UTC, daniel-montalvo requested changes

2021-08-24 08:07 UTC, daniel-montalvo commented on pages/design/process.md
> +- No changes or only changes that _do not_ require a "Call for Review" is made to the rule after "Call for Review" is launched.
```suggestion
- No changes or only changes that _do not_ require a "Call for Review" are made to the rule after "Call for Review" is launched.
```

2021-08-24 08:07 UTC, daniel-montalvo commented on pages/design/process.md
> +- Changes that do require a "Call for Review" is made to the rule after "Call for Review" is launched.
```suggestion
- Changes that do require a "Call for Review" are made to the rule after "Call for Review" is launched.
```

2021-08-24 08:07 UTC, daniel-montalvo commented on pages/design/process.md
> +  - For changes that _does not_ require a "Call for Review" (see above): Implement changes as soon as possible, and dismiss outdated reviews (to let all reviewers know that the pull request is review
```suggestion
  - For changes that _do not_ require a "Call for Review" (see above): Implement changes as soon as possible, and dismiss outdated reviews (to let all reviewers know that the pull request is review ready), and request a new review from that person.
```

2021-08-24 08:07 UTC, daniel-montalvo commented on pages/design/process.md
> +  - For changes that _does_ require a new "Call for Review": Evaluate whether "Call for Review" should be allowed to run out before changes are made, or if changes should be made right away, but with
```suggestion
  - For changes that _do_ require a new "Call for Review": Evaluate whether "Call for Review" should be allowed to run out before changes are made, or if changes should be made right away, but with a note that a new "Call for Review" will be required.
```

2021-08-24 08:07 UTC, daniel-montalvo commented on pages/design/process.md
> +- When commenting, please note whether you consider the suggested changes to be substantial or not (whether the change falls into the category of changes that do require a "Call for Review", or the o
```suggestion
- When commenting, please note whether you consider the suggested changes to be substantial or not (whether the change falls into the category of changes that do require a "Call for Review", or the ones that do not require a "Call for Review").
```

2021-09-02 14:15 UTC, merged