Update aria-hidden-no-focusable-content-6cfa84.md
act-rules/act-rules.github.io pull request #1725
Opened 2021-09-29 18:47 UTC by kengdoj

In response to TF survey comments:

- [ ]  remove 1.3.1
- [ ] Regarding merging with presentational children, TF feels the rules should be kept separate						
- [ ] We'll want to cross-link between the two suggested merge rules. Needs to explain why they are similar						
- [ ] Need to resolve 1386 and 1444 first						
- [ ] Daniel will remove "work in progress" from the background

Closes issue(s):

- closes #XXX (ADD ISSUE NUMBER HERE)

Need for Call for Review:
<< choose one of the following and remove the rest >>
<< check [Process Document on Call for Review](https://act-rules.github.io/pages/design/process/#call-for-review) >>
This can be merged with 1 approval << choose reason: editorial changes to website/test code, adding new contributor, other (explain). >>
This will not require a Call for Review << choose reason(s): editorial changes (including to the applicability, expectation or examples section), changes to assumptions, background, accessibility support, change to website/test code (not rule), other (explain). >>
This will require a 1 week Call for Review << small changes affecting a small number of test cases, if in doubt do not use this. >>
This will require a 2 weeks Call for Review << new rule, or substantial changes affecting a large number of test cases, if in doubt, use this. >>

---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2021-09-30 19:08 UTC, carlosapaduarte requested changes

2021-09-30 19:08 UTC, carlosapaduarte commented on _rules/aria-hidden-no-focusable-content-6cfa84.md
> +**Note:** Using `aria-hidden="false"` on a descendant of an element with `aria-hidden="true"` **does not** expose that element. An element with `aria-hidden="true"` hides itself and all its content a
```suggestion
**Note:** Using `aria-hidden="false"` on a descendant of an element with `aria-hidden="true"` **does not** expose that element. An element with `aria-hidden="true"` hides itself, all its content and all its descendants from assistive technologies.
```

2021-10-01 20:51 UTC, kengdoj commented on _rules/aria-hidden-no-focusable-content-6cfa84.md
> +**Note:** Using `aria-hidden="false"` on a descendant of an element with `aria-hidden="true"` **does not** expose that element. An element with `aria-hidden="true"` hides itself and all its content a
thanks @carlosapaduarte!

2021-12-09 13:56 UTC, tbostic32 approved these changes

2021-12-09 14:27 UTC, WilcoFiers approved these changes

2021-12-09 14:33 UTC, merged