scrollable-element-keyboard: inapplicable example 5 started failing
act-rules/act-rules.github.io pull request #1743
Opened 2021-11-17 13:51 UTC by WilcoFiers

Chrome 96 changed how it padding-right interacts with scrollbar. In previous versions, and still in all other major browser it would pretend right padding does not exist for the purpose of scrolling. Effectively just making the box wider by the amount of padding-right that it has, and pretending that padding-right is 0. That's no longer the case, and so this inapplicable example was suddenly a failure.

I've updated this example so that it functions consistently again in all major browsers.

**Edge 95**

![Inapplicable example 5, text can not be scrolled off screen in Edge 95](https://user-images.githubusercontent.com/530687/142212566-b0eb4315-90d5-4a18-8711-b298b5c9ee14.png)

**Chrome 96**

![Inapplicable example 5, text scrolled off screen in Chrome 96](https://user-images.githubusercontent.com/530687/142212466-5cbca546-0ea2-426c-93e4-5dc3f4556166.png)

Here's a link to the example so you can see for yourself:
https://act-rules.github.io/testcases/0ssw9k/9646f97144271b3e95b6648f5814085ddaa8ee08.html

Need for Call for Review: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2021-11-17 14:19 UTC, carlosapaduarte approved these changes

2021-11-17 14:46 UTC, Jym77 requested changes
I'm afraid the rabbit hole goes deeper 😕 

* It seems that it is the definition of [Scrollable elements](https://act-rules.github.io/rules/0ssw9k#scrollable-element) that is now browser dependent, not just this rule. I assume because `scrollWidth` (or `clientWidth`?) is now browser dependent. We should record the information at the correct place. Note that [`scrollWidth`](https://www.w3.org/TR/cssom-view/#dom-element-scrollwidth) goes to 
   > Return the width of the element’s [scrolling area](https://www.w3.org/TR/cssom-view/#scrolling-area). 
   
   in turn leading to
   > The right-most edge of the element’s right padding edge 

   So I would argue that Chrome is actually correct in scrolling through all the padding 🤔 (in any case, it is worth checking why they decided to change the value of either `scrollWidth` or `clientWidth`: either there has been some recent change in CSS and we can expect everybody to follow suit shortly, or something weird is happening).

* The old example is now code that is Inapplicable on some browsers, but Failed on others. But then, as I understand when the page loads (on Chrome), all the text is nonetheless visible (it is only some padding area that is "hidden"). So, even without any possibility to scroll it, nothing would be missing and I am not sure that it would fail 2.1.1 Keyboard. 

   In this case, it means that this code is actually a false positive on Chrome (failing the rule, not the SC), which is bad.

2021-11-17 14:46 UTC, Jym77 commented on _rules/scrollable-element-keyboard-accessible-0ssw9k.md
> +There are also differences between browsers in if they make right padding scrollable. While some browsers allow scrolling the full border-width of the content of a scrollable region, others constrain
```suggestion
Some browsers restrict scrolling to the [content box](https://drafts.csswg.org/css-box-4/#content-box) of elements; while others allow to scroll the full [border box](https://drafts.csswg.org/css-box-4/#border-box), hence including the element's padding. This results in some elements being scrollable with a browser but not with another.
```

2021-11-17 14:46 UTC, Jym77 commented on _rules/scrollable-element-keyboard-accessible-0ssw9k.md
>  	<div style="width: 520px">
I'm not sure the example illustrates the same thing now.
The old example is great at seeing if tools take `padding` into consideration: without `padding` it looks like a `520px` element inside a `500px` one and requires scrolling, with padding the inner element is less wide. No, the inner element is always less wide than the outer, and the example doesn't differentiate tools on whether they use `padding` or not.

2021-11-17 15:26 UTC, Jym77 approved these changes

2021-11-23 11:21 UTC, HelenBurge approved these changes

2021-11-23 13:19 UTC, merged