Update aria-hidden-no-focusable-content-6cfa84.md
act-rules/act-rules.github.io pull request #1748
Opened 2021-11-21 21:16 UTC by HelenBurge

Removed 1.3.1 and 4.1.2 as feel this applies to 2.4.3 more (a single checkpoint)

Asked to make sure there is only 1 SC dependency and this rule fits more to 2.4.3 than 1.3.1 and 4.1.2.

Closes issue(s):

N/A

Need for Call for Review:
This will require a 1 week Call for Review

2021-12-23 09:19 UTC, carlosapaduarte commented
I don't agree this impacts 2.4.3. What this is checking is that something that is in the sequential focus navigation is not aria-hidden. It won't have an impact on the focus order (because it is not taken out of the sequential focus navigation), so it should not impact 2.4.3.

On the other hand, I maintain that it fails 4.1.2 (you won't be able to programatically determine the role of the element if it is aria-hidden) and 1.3.1 (because it will prevent programatic access to information of focusable elements).

2021-12-23 09:19 UTC, carlosapaduarte requested changes
https://github.com/act-rules/act-rules.github.io/pull/1748#issuecomment-1000158326

2022-01-04 12:04 UTC, HelenBurge commented
I am in 2 minds, I think 2.4.3 should fail here as it is about the focusable order, not the DOM order, and this rule is testing that child elements of a hidden attribute are not in the focus order, or that aria-hidden is not used on a parent item of something that should be in the focus order.

However, the state that relates to 4.1.2 can also be valid here. So I will leave this for more thoughts before taking any action.

2022-01-13 15:34 UTC, closed without merging

2022-01-13 15:35 UTC, HelenBurge commented
Carlos is right