Adding DPUB use cases
act-rules/act-rules.github.io pull request #1760
Opened 2021-11-22 14:44 UTC by daniel-montalvo

Adds DPUB use cases.

Closes issue(s):

- closes #1670 

Need for Call for Review:
This will require a 1 week Call for Review << small changes affecting a small number of test cases, if in doubt do not use this. >>

---

## Pull Request Etiquette

### **When creating PR:**

- [x] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [x] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2021-11-23 08:42 UTC, daniel-montalvo commented on _rules/link-non-empty-accessible-name-c487ae.md
> +See [<span onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref link">ACT rules</span
```suggestion
See [<span onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref">ACT rules</span>]
```

2021-11-23 08:44 UTC, daniel-montalvo commented on _rules/link-non-empty-accessible-name-c487ae.md
> +See [<span onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref link"></span
```suggestion
See [<span onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref"></span>]
```

2021-11-23 10:28 UTC, colabottles approved these changes

2021-11-23 11:03 UTC, WilcoFiers submitted a review, later dismissed
Couple of points:
- You'll need to update the applicability, so that it uses inheriting semantic role.
- You should probably also update the acc support section to point out that these doc-* roles aren't widely supported.
- Do you want to add yourself to the authors list?

2021-11-23 11:03 UTC, WilcoFiers commented on _rules/link-non-empty-accessible-name-c487ae.md
> +See [<span onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref">ACT rules</span>]
I'm a little hesitant to say this passes SC 4.1.2. This wouldn't be accessibility supported. Perhaps what we need to do is put these on actual anchor elements?

2021-12-02 12:54 UTC, Jym77 submitted a review, later dismissed

2021-12-02 12:54 UTC, Jym77 commented on _rules/link-non-empty-accessible-name-c487ae.md
> +See [<a onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref">ACT rules</a>]
This is not a `span` element 🙈 
```suggestion
See [<span onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref">ACT rules</span>].
```

2021-12-02 12:54 UTC, Jym77 commented on _rules/link-non-empty-accessible-name-c487ae.md
> +See [<a onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref"></a>]
```suggestion
See [<span onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref"></span>].
```

2021-12-02 12:54 UTC, Jym77 commented on _rules/link-non-empty-accessible-name-c487ae.md
> +See [<a onclick="location.href='https://act-rules.github.io/'" role="doc-biblioref"></a>]
Maybe adding an image inside the `span` here. Visually, nothing is displayed and there is almost nowhere to actually click, which is at least weird.
Adding [this image](https://github.com/act-rules/act-rules.github.io/blob/develop/test-assets/shared/act-logo.png) with an empty `alt` would be better, I think.

2021-12-02 12:54 UTC, Jym77 commented on _rules/link-non-empty-accessible-name-c487ae.md
> +[inheriting semantic role]: #inheriting-semantic-role 'Definition of inheriting semantic role'
```suggestion
[inheriting semantic role]: #inheriting-semantic 'Definition of inheriting semantic role'
```
The key is only `inheriting-semantic`, that should fix the test 🤞

2021-12-02 14:14 UTC, colabottles approved these changes

2021-12-07 11:58 UTC, daniel-montalvo commented
Hey @Jym77 

`span` elements were turned into `a` elements based on @wilcofiers  suggestion that `span` elements would probably not pass 4.1.2 in this context. I should change the description rather than the examples themselves. Would you not agree with this?

2021-12-14 15:40 UTC, WilcoFiers requested changes
Tests are failing. Suggest doing things like this. It keeps things consistent with rules like Link is descriptive.

2021-12-14 15:40 UTC, WilcoFiers commented on _rules/link-non-empty-accessible-name-c487ae.md
> +This rule applies to any [HTML element][] that is an [inheriting semantic][inheriting semantic role] `link` [included in the accessibility tree][].
Suggest you do them the other way around:

```suggestion
This rule applies to any [HTML element][] that is an [inheriting semantic][] `link` [included in the accessibility tree][].
```

2021-12-14 15:40 UTC, WilcoFiers commented on _rules/link-non-empty-accessible-name-c487ae.md
> +- Accessibility support for [inheriting semantic][inheriting-semantic] links may vary depending on the assistive technology in use.
```suggestion
- Accessibility support for [inheriting semantic][] links may vary depending on the assistive technology in use.
```

2021-12-14 15:40 UTC, WilcoFiers commented on _rules/link-non-empty-accessible-name-c487ae.md
> +This `a` element has an [inheriting semantic role][] of `link` given by its `role="doc-biblioref"` attribute as well as an [accessible name] given by its child text node.
```suggestion
This `a` element has an [inheriting semantic][] `link` given by its `role="doc-biblioref"` attribute as well as an [accessible name] given by its child text node.
```

2021-12-14 15:40 UTC, WilcoFiers commented on _rules/link-non-empty-accessible-name-c487ae.md
> +This `a` element has an [inheriting semantic role][] of `link` given by its `role="doc-biblioref"` attribute but it has an empty [accessible name].
```suggestion
This `a` element has an [inheriting semantic][] `link` given by its `role="doc-biblioref"` attribute but it has an empty [accessible name].
```

2021-12-14 15:54 UTC, colabottles approved these changes

2021-12-16 11:46 UTC, Jym77 approved these changes

2021-12-17 14:49 UTC, WilcoFiers commented on _rules/link-non-empty-accessible-name-c487ae.md
> +This rule applies to any [HTML element][] that is an [inheriting semantic][inheriting semantic] `link` [included in the accessibility tree][].
Think you can simplify this:

```suggestion
This rule applies to any [HTML element][] that is an [inheriting semantic][] `link` [included in the accessibility tree][].
```

2021-12-21 09:08 UTC, carlosapaduarte reviewed
I understand why you are not convinced by the accessibility support note you added. I've tried to update it to better match Wilco's concerns. I'll leave it to your judgment on whether this is useful or not.

2021-12-21 09:08 UTC, carlosapaduarte commented on _rules/link-non-empty-accessible-name-c487ae.md
> +- Accessibility support for [inheriting semantic][] links may vary depending on the assistive technology in use.
```suggestion
- Accessibility support for some elements inheriting the semantic role of `link` (e.g. elements with `doc-*` attributes) may vary depending on the assistive technology in use.
```

2021-12-27 11:32 UTC, carlosapaduarte requested changes
editorial

2021-12-27 11:32 UTC, carlosapaduarte commented on _rules/link-non-empty-accessible-name-c487ae.md
> +This `a` element has an [inheriting semantic][] `link` given by its `role="doc-biblioref"` attribute as well as an [accessible name] given by its child text node.
To be consistent with the way the applicability is written. 

```suggestion
This `a` element is an [inheriting semantic][] `link` given by its `role="doc-biblioref"` attribute as well as an [accessible name] given by its child text node.
```

2021-12-27 11:32 UTC, carlosapaduarte commented on _rules/link-non-empty-accessible-name-c487ae.md
> +This `a` element has an [inheriting semantic][] `link` given by its `role="doc-biblioref"` attribute but it has an empty [accessible name].
To be consistent with the way the applicability is written. 

```suggestion
This `a` element is an [inheriting semantic][] `link` given by its `role="doc-biblioref"` attribute but it has an empty [accessible name].
```

2021-12-29 00:19 UTC, colabottles approved these changes

2022-01-03 15:18 UTC, daniel-montalvo commented on _rules/link-non-empty-accessible-name-c487ae.md
> +- Accessibility support for [inheriting semantic][] links may vary depending on the assistive technology in use.
```suggestion
- Accessibility support for some elements inheriting the semantic role of `link` (e.g. elements with `doc-*` attributes) may vary depending on the assistive technology in use.
```
I seem to have dropped this accidentally @carlosapaduarte  Bringing it back.

2022-01-10 13:07 UTC, WilcoFiers approved these changes

2022-01-12 01:04 UTC, kherr-a11y approved these changes

2022-01-20 14:34 UTC, merged