Update format for rule names
act-rules/act-rules.github.io pull request #1841
Opened 2022-05-02 10:56 UTC by WilcoFiers

- Remove backticks
- Remove single quotes
- Always capitalize

We have a number of places where rendering back ticks in rule names has proven difficult. We've previously stripped out the back ticks, but this ends up looking kinda strange, with some rule names capitalised and others not for no obvious reason. 

Need for Call for Review: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2022-05-05 18:54 UTC, kengdoj requested changes
added element after audio and video in some of the rules

2022-05-05 18:54 UTC, kengdoj commented on _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
> +name: Audio or video avoids automatically playing audio
```suggestion
name: Audio element or video element avoids automatically playing audio
```

2022-05-05 18:54 UTC, kengdoj commented on _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
> +name: Audio or video that plays automatically has no audio that lasts more than 3 seconds
```suggestion
name: Audio element or video element that plays automatically has no audio that lasts more than 3 seconds
```

2022-05-05 18:54 UTC, kengdoj commented on _rules/auto-play-audio-has-control-mechanism-4c31df.md
> +name: Audio or video that plays automatically has a control mechanism
```suggestion
name: Audio element or video element that plays automatically has a control mechanism
```

2022-05-17 22:30 UTC, kengdoj approved these changes

2022-05-18 18:43 UTC, carlosapaduarte requested changes
Missed a couple

2022-05-18 18:43 UTC, carlosapaduarte commented on _rules/meta-refresh-no-delay-bc659a.md
> +name: Meta element has no refresh delay'
```suggestion
name: Meta element has no refresh delay
```

2022-05-18 18:43 UTC, carlosapaduarte commented on _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
> +name: Headers attribute specified on a cell refers to cells in the same table element'
```suggestion
name: Headers attribute specified on a cell refers to cells in the same table element
```

2022-05-19 10:53 UTC, Jym77 approved these changes

2022-05-23 20:20 UTC, colabottles approved these changes

2022-05-30 11:38 UTC, merged